// flow-typed signature: 1dab021a30a976a8c07c117d5a962528
// flow-typed version: <<STUB>>/terminal-kit_v^1.17.11/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terminal-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terminal-kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terminal-kit/demo/spaceship' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/autoComplete' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/bar' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/detectTerminal' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/Button' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/ColumnMenu' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/Container' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/Document' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/DropDownMenu' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/Element' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/Form' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/Layout' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/RowMenu' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/Text' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/document/TextInput' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/fileInput' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/gpm' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/gridMenu' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/hslConverter' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/image' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/inputField' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/misc' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/progressBar' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/Rect' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/ScreenBuffer' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/ScreenBufferHD' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/singleColumnMenu' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/singleLineMenu' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/slowTyping' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/spChars' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/atomic-terminal' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/eterm-256color' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/eterm' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/gnome-256color' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/gnome' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/konsole-256color' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/konsole' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/linux' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/none' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/rxvt-256color' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/rxvt' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/xfce' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/xterm-256color.generic' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/xterm-256color' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/xterm-truecolor.generic' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/xterm-truecolor' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/xterm.generic' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termconfig/xterm' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/Terminal' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/terminfo' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/termkit' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/TextBuffer' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/tty' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/windows' {
  declare module.exports: any;
}

declare module 'terminal-kit/lib/yesOrNo' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/24bits-colors-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/256colors-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/all-event-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/async-auto-completer-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/crash-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/cursor-color-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/cwd-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/detect-terminal-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/document/column-menu-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/document/document-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/document/drop-down-menu-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/document/focus-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/document/form-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/document/layout-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/document/row-menu-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/document/text-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/draw-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/endian-benchmark' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/eraseArea' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/event-loop-hanging' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/file-input-doc1' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/format-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/fullwidth-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/get-color-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/get-palette-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/gpm-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/grid-menu-doc1' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/grid-menu-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/image-viewer' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/input-field-doc1' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/input-field-doc2' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/input-field-doc3' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/input-field-doc4' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/input-field-shell-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/input-field-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/is-tty' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/key-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/linux-console-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/mouse-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/notify-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/pipe-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/progress-bar-doc1' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/progress-bar-doc2' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/progress-bar-items-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/progress-bar-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/resize' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/screenbuffer-compatible-methods' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/screenbuffer-hd-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/screenbuffer-put-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/screenbuffer-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/scrolling-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/set-color-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/single-column-menu-doc1' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/single-column-menu-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/single-column-menu-todoc2' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/single-line-menu-doc1' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/single-line-menu-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/slow-typing-doc1' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/slow-typing-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/style-doc' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/style-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/textbuffer-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/tty-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/underscore-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/window-title-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/wordwrap' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/write-anywhere' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/yes-no-doc1' {
  declare module.exports: any;
}

declare module 'terminal-kit/sample/yes-no-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/test/screenbuffer-rect-test' {
  declare module.exports: any;
}

declare module 'terminal-kit/test/terminal-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terminal-kit/demo/spaceship.js' {
  declare module.exports: $Exports<'terminal-kit/demo/spaceship'>;
}
declare module 'terminal-kit/lib/autoComplete.js' {
  declare module.exports: $Exports<'terminal-kit/lib/autoComplete'>;
}
declare module 'terminal-kit/lib/bar.js' {
  declare module.exports: $Exports<'terminal-kit/lib/bar'>;
}
declare module 'terminal-kit/lib/detectTerminal.js' {
  declare module.exports: $Exports<'terminal-kit/lib/detectTerminal'>;
}
declare module 'terminal-kit/lib/document/Button.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/Button'>;
}
declare module 'terminal-kit/lib/document/ColumnMenu.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/ColumnMenu'>;
}
declare module 'terminal-kit/lib/document/Container.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/Container'>;
}
declare module 'terminal-kit/lib/document/Document.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/Document'>;
}
declare module 'terminal-kit/lib/document/DropDownMenu.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/DropDownMenu'>;
}
declare module 'terminal-kit/lib/document/Element.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/Element'>;
}
declare module 'terminal-kit/lib/document/Form.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/Form'>;
}
declare module 'terminal-kit/lib/document/Layout.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/Layout'>;
}
declare module 'terminal-kit/lib/document/RowMenu.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/RowMenu'>;
}
declare module 'terminal-kit/lib/document/Text.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/Text'>;
}
declare module 'terminal-kit/lib/document/TextInput.js' {
  declare module.exports: $Exports<'terminal-kit/lib/document/TextInput'>;
}
declare module 'terminal-kit/lib/fileInput.js' {
  declare module.exports: $Exports<'terminal-kit/lib/fileInput'>;
}
declare module 'terminal-kit/lib/gpm.js' {
  declare module.exports: $Exports<'terminal-kit/lib/gpm'>;
}
declare module 'terminal-kit/lib/gridMenu.js' {
  declare module.exports: $Exports<'terminal-kit/lib/gridMenu'>;
}
declare module 'terminal-kit/lib/hslConverter.js' {
  declare module.exports: $Exports<'terminal-kit/lib/hslConverter'>;
}
declare module 'terminal-kit/lib/image.js' {
  declare module.exports: $Exports<'terminal-kit/lib/image'>;
}
declare module 'terminal-kit/lib/inputField.js' {
  declare module.exports: $Exports<'terminal-kit/lib/inputField'>;
}
declare module 'terminal-kit/lib/misc.js' {
  declare module.exports: $Exports<'terminal-kit/lib/misc'>;
}
declare module 'terminal-kit/lib/progressBar.js' {
  declare module.exports: $Exports<'terminal-kit/lib/progressBar'>;
}
declare module 'terminal-kit/lib/Rect.js' {
  declare module.exports: $Exports<'terminal-kit/lib/Rect'>;
}
declare module 'terminal-kit/lib/ScreenBuffer.js' {
  declare module.exports: $Exports<'terminal-kit/lib/ScreenBuffer'>;
}
declare module 'terminal-kit/lib/ScreenBufferHD.js' {
  declare module.exports: $Exports<'terminal-kit/lib/ScreenBufferHD'>;
}
declare module 'terminal-kit/lib/singleColumnMenu.js' {
  declare module.exports: $Exports<'terminal-kit/lib/singleColumnMenu'>;
}
declare module 'terminal-kit/lib/singleLineMenu.js' {
  declare module.exports: $Exports<'terminal-kit/lib/singleLineMenu'>;
}
declare module 'terminal-kit/lib/slowTyping.js' {
  declare module.exports: $Exports<'terminal-kit/lib/slowTyping'>;
}
declare module 'terminal-kit/lib/spChars.js' {
  declare module.exports: $Exports<'terminal-kit/lib/spChars'>;
}
declare module 'terminal-kit/lib/termconfig/atomic-terminal.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/atomic-terminal'>;
}
declare module 'terminal-kit/lib/termconfig/eterm-256color.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/eterm-256color'>;
}
declare module 'terminal-kit/lib/termconfig/eterm.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/eterm'>;
}
declare module 'terminal-kit/lib/termconfig/gnome-256color.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/gnome-256color'>;
}
declare module 'terminal-kit/lib/termconfig/gnome.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/gnome'>;
}
declare module 'terminal-kit/lib/termconfig/konsole-256color.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/konsole-256color'>;
}
declare module 'terminal-kit/lib/termconfig/konsole.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/konsole'>;
}
declare module 'terminal-kit/lib/termconfig/linux.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/linux'>;
}
declare module 'terminal-kit/lib/termconfig/none.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/none'>;
}
declare module 'terminal-kit/lib/termconfig/rxvt-256color.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/rxvt-256color'>;
}
declare module 'terminal-kit/lib/termconfig/rxvt.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/rxvt'>;
}
declare module 'terminal-kit/lib/termconfig/xfce.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/xfce'>;
}
declare module 'terminal-kit/lib/termconfig/xterm-256color.generic.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/xterm-256color.generic'>;
}
declare module 'terminal-kit/lib/termconfig/xterm-256color.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/xterm-256color'>;
}
declare module 'terminal-kit/lib/termconfig/xterm-truecolor.generic.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/xterm-truecolor.generic'>;
}
declare module 'terminal-kit/lib/termconfig/xterm-truecolor.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/xterm-truecolor'>;
}
declare module 'terminal-kit/lib/termconfig/xterm.generic.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/xterm.generic'>;
}
declare module 'terminal-kit/lib/termconfig/xterm.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termconfig/xterm'>;
}
declare module 'terminal-kit/lib/Terminal.js' {
  declare module.exports: $Exports<'terminal-kit/lib/Terminal'>;
}
declare module 'terminal-kit/lib/terminfo.js' {
  declare module.exports: $Exports<'terminal-kit/lib/terminfo'>;
}
declare module 'terminal-kit/lib/termkit.js' {
  declare module.exports: $Exports<'terminal-kit/lib/termkit'>;
}
declare module 'terminal-kit/lib/TextBuffer.js' {
  declare module.exports: $Exports<'terminal-kit/lib/TextBuffer'>;
}
declare module 'terminal-kit/lib/tty.js' {
  declare module.exports: $Exports<'terminal-kit/lib/tty'>;
}
declare module 'terminal-kit/lib/windows.js' {
  declare module.exports: $Exports<'terminal-kit/lib/windows'>;
}
declare module 'terminal-kit/lib/yesOrNo.js' {
  declare module.exports: $Exports<'terminal-kit/lib/yesOrNo'>;
}
declare module 'terminal-kit/sample/24bits-colors-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/24bits-colors-test'>;
}
declare module 'terminal-kit/sample/256colors-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/256colors-test'>;
}
declare module 'terminal-kit/sample/all-event-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/all-event-test'>;
}
declare module 'terminal-kit/sample/async-auto-completer-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/async-auto-completer-test'>;
}
declare module 'terminal-kit/sample/crash-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/crash-test'>;
}
declare module 'terminal-kit/sample/cursor-color-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/cursor-color-test'>;
}
declare module 'terminal-kit/sample/cwd-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/cwd-test'>;
}
declare module 'terminal-kit/sample/detect-terminal-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/detect-terminal-test'>;
}
declare module 'terminal-kit/sample/document/column-menu-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/document/column-menu-test'>;
}
declare module 'terminal-kit/sample/document/document-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/document/document-test'>;
}
declare module 'terminal-kit/sample/document/drop-down-menu-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/document/drop-down-menu-test'>;
}
declare module 'terminal-kit/sample/document/focus-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/document/focus-test'>;
}
declare module 'terminal-kit/sample/document/form-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/document/form-test'>;
}
declare module 'terminal-kit/sample/document/layout-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/document/layout-test'>;
}
declare module 'terminal-kit/sample/document/row-menu-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/document/row-menu-test'>;
}
declare module 'terminal-kit/sample/document/text-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/document/text-test'>;
}
declare module 'terminal-kit/sample/draw-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/draw-test'>;
}
declare module 'terminal-kit/sample/endian-benchmark.js' {
  declare module.exports: $Exports<'terminal-kit/sample/endian-benchmark'>;
}
declare module 'terminal-kit/sample/eraseArea.js' {
  declare module.exports: $Exports<'terminal-kit/sample/eraseArea'>;
}
declare module 'terminal-kit/sample/event-loop-hanging.js' {
  declare module.exports: $Exports<'terminal-kit/sample/event-loop-hanging'>;
}
declare module 'terminal-kit/sample/file-input-doc1.js' {
  declare module.exports: $Exports<'terminal-kit/sample/file-input-doc1'>;
}
declare module 'terminal-kit/sample/format-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/format-test'>;
}
declare module 'terminal-kit/sample/fullwidth-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/fullwidth-test'>;
}
declare module 'terminal-kit/sample/get-color-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/get-color-test'>;
}
declare module 'terminal-kit/sample/get-palette-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/get-palette-test'>;
}
declare module 'terminal-kit/sample/gpm-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/gpm-test'>;
}
declare module 'terminal-kit/sample/grid-menu-doc1.js' {
  declare module.exports: $Exports<'terminal-kit/sample/grid-menu-doc1'>;
}
declare module 'terminal-kit/sample/grid-menu-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/grid-menu-test'>;
}
declare module 'terminal-kit/sample/image-viewer.js' {
  declare module.exports: $Exports<'terminal-kit/sample/image-viewer'>;
}
declare module 'terminal-kit/sample/input-field-doc1.js' {
  declare module.exports: $Exports<'terminal-kit/sample/input-field-doc1'>;
}
declare module 'terminal-kit/sample/input-field-doc2.js' {
  declare module.exports: $Exports<'terminal-kit/sample/input-field-doc2'>;
}
declare module 'terminal-kit/sample/input-field-doc3.js' {
  declare module.exports: $Exports<'terminal-kit/sample/input-field-doc3'>;
}
declare module 'terminal-kit/sample/input-field-doc4.js' {
  declare module.exports: $Exports<'terminal-kit/sample/input-field-doc4'>;
}
declare module 'terminal-kit/sample/input-field-shell-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/input-field-shell-test'>;
}
declare module 'terminal-kit/sample/input-field-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/input-field-test'>;
}
declare module 'terminal-kit/sample/is-tty.js' {
  declare module.exports: $Exports<'terminal-kit/sample/is-tty'>;
}
declare module 'terminal-kit/sample/key-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/key-test'>;
}
declare module 'terminal-kit/sample/linux-console-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/linux-console-test'>;
}
declare module 'terminal-kit/sample/mouse-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/mouse-test'>;
}
declare module 'terminal-kit/sample/notify-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/notify-test'>;
}
declare module 'terminal-kit/sample/pipe-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/pipe-test'>;
}
declare module 'terminal-kit/sample/progress-bar-doc1.js' {
  declare module.exports: $Exports<'terminal-kit/sample/progress-bar-doc1'>;
}
declare module 'terminal-kit/sample/progress-bar-doc2.js' {
  declare module.exports: $Exports<'terminal-kit/sample/progress-bar-doc2'>;
}
declare module 'terminal-kit/sample/progress-bar-items-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/progress-bar-items-test'>;
}
declare module 'terminal-kit/sample/progress-bar-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/progress-bar-test'>;
}
declare module 'terminal-kit/sample/resize.js' {
  declare module.exports: $Exports<'terminal-kit/sample/resize'>;
}
declare module 'terminal-kit/sample/screenbuffer-compatible-methods.js' {
  declare module.exports: $Exports<'terminal-kit/sample/screenbuffer-compatible-methods'>;
}
declare module 'terminal-kit/sample/screenbuffer-hd-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/screenbuffer-hd-test'>;
}
declare module 'terminal-kit/sample/screenbuffer-put-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/screenbuffer-put-test'>;
}
declare module 'terminal-kit/sample/screenbuffer-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/screenbuffer-test'>;
}
declare module 'terminal-kit/sample/scrolling-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/scrolling-test'>;
}
declare module 'terminal-kit/sample/set-color-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/set-color-test'>;
}
declare module 'terminal-kit/sample/single-column-menu-doc1.js' {
  declare module.exports: $Exports<'terminal-kit/sample/single-column-menu-doc1'>;
}
declare module 'terminal-kit/sample/single-column-menu-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/single-column-menu-test'>;
}
declare module 'terminal-kit/sample/single-column-menu-todoc2.js' {
  declare module.exports: $Exports<'terminal-kit/sample/single-column-menu-todoc2'>;
}
declare module 'terminal-kit/sample/single-line-menu-doc1.js' {
  declare module.exports: $Exports<'terminal-kit/sample/single-line-menu-doc1'>;
}
declare module 'terminal-kit/sample/single-line-menu-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/single-line-menu-test'>;
}
declare module 'terminal-kit/sample/slow-typing-doc1.js' {
  declare module.exports: $Exports<'terminal-kit/sample/slow-typing-doc1'>;
}
declare module 'terminal-kit/sample/slow-typing-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/slow-typing-test'>;
}
declare module 'terminal-kit/sample/style-doc.js' {
  declare module.exports: $Exports<'terminal-kit/sample/style-doc'>;
}
declare module 'terminal-kit/sample/style-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/style-test'>;
}
declare module 'terminal-kit/sample/test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/test'>;
}
declare module 'terminal-kit/sample/textbuffer-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/textbuffer-test'>;
}
declare module 'terminal-kit/sample/tty-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/tty-test'>;
}
declare module 'terminal-kit/sample/underscore-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/underscore-test'>;
}
declare module 'terminal-kit/sample/window-title-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/window-title-test'>;
}
declare module 'terminal-kit/sample/wordwrap.js' {
  declare module.exports: $Exports<'terminal-kit/sample/wordwrap'>;
}
declare module 'terminal-kit/sample/write-anywhere.js' {
  declare module.exports: $Exports<'terminal-kit/sample/write-anywhere'>;
}
declare module 'terminal-kit/sample/yes-no-doc1.js' {
  declare module.exports: $Exports<'terminal-kit/sample/yes-no-doc1'>;
}
declare module 'terminal-kit/sample/yes-no-test.js' {
  declare module.exports: $Exports<'terminal-kit/sample/yes-no-test'>;
}
declare module 'terminal-kit/test/screenbuffer-rect-test.js' {
  declare module.exports: $Exports<'terminal-kit/test/screenbuffer-rect-test'>;
}
declare module 'terminal-kit/test/terminal-test.js' {
  declare module.exports: $Exports<'terminal-kit/test/terminal-test'>;
}
